export const ROUTES = {
  HOME: "/",
  PROFILE: "/profile",
  ACCOUNT: {
    ORDERS: "/profile/orders",
    WISHLIST: "/profile/wishlist",
    INFO: "/profile",
    ADDRESSES: "/profile/addresses",
    ADD_ADDRESS: "/profile/addresses/add",
    EDIT_ADDRESS: "/profile/addresses/edit/:id",
    PAYMENT: "/profile/payment-method",
    CHANGE_PASSWORD: "/profile/change-password",
  },
  PRODUCTS: "/products",
  SHIRTS: "/shirts",
  TSHIRTS: "/tshirts",
  JEANS: "/jeans",
  INFO: {
    CONTACT: "/contact-us",
    ABOUT: "/about-us",
    ABOUT_DETAIL: "/about-us/:id",
    TRACKING: "/tracking-order",
    BLOG: "/blog",
    BLOG_DETAIL: "/blog/:id",
    FAQ: "/faq",
    REFUND: "/return-refund-policy",
    PRIVACY: "/privacy-policy",
    TERMS: "/terms-condition",
    CANCELLATION: "/cancellation-policy",
  },
  AUTH: {
    SIGNIN: "/auth/signin",
    LOGIN: "/auth/login",
    SIGNUP: "/auth/signup",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_OTP: "/auth/verify-otp",
  },
} as const;
